### PR TITLE
mAP testing

### PR DESCRIPTION
**Pull request by mhuesch**
Hi Roddy,

Chad and I took a look at the MAP code and, based on this reference implementation we found (https://github.com/benhamner/Metrics/blob/master/Python/ml_metrics/average_precision.py) made a few tweaks. The first commit breaks stuff into functions so we could more easily test.

The "real" changes are:
1) Only add to `sum_ap` if the entry is "correct" (i.e. has a 1 as it's key in `correct_map`). We think this is in keeping with the reference and makes sense (otherwise false negatives add to `sum_ap`).
2) To calculate MAP, divide `sum_ap` by the number of "actuals" - the number of 1 values in `correct map`. This seems to agree with the above linked reference. For example, this is how I checked the test case I added:
```
>>> from average_precision import *
>>> apk([0,2,4,5],[0,1,2,3,4,5])
0.7333333333333333
```

I have only read about MAP on a few occasions now but this makes sense to me and agrees with what I interpret the reference implementation to say. Let me know what you think!

### CODE REVIEW

**Comment by mhuesch** [comment]
I've evaluated one of my test runs using these changes and it seems like the MAP scores of the random binary & prior samples are scored much lower than how the `cp6_eval.py` on master scores them.

**MAP_testing branch evaluations**
[eval_rBinary.log.txt](https://github.com/GaloisInc/ppaml-cp6/files/58966/eval_rBinary.log.txt)
[eval_real.log.txt](https://github.com/GaloisInc/ppaml-cp6/files/58967/eval_real.log.txt)
[eval_rPrior.log.txt](https://github.com/GaloisInc/ppaml-cp6/files/58968/eval_rPrior.log.txt)

**master branch evaluations**
[master_eval_rBinary.log.txt](https://github.com/GaloisInc/ppaml-cp6/files/58970/master_eval_rBinary.log.txt)
[master_eval_real.log.txt](https://github.com/GaloisInc/ppaml-cp6/files/58972/master_eval_real.log.txt)
[master_eval_rPrior.log.txt](https://github.com/GaloisInc/ppaml-cp6/files/58971/master_eval_rPrior.log.txt)

**Comment by cscherrer** [comment]
Here's a nice description of MAP from Kevin's Murphy's machine learning book:

-----------------------
map
-----------------------

Going over this with Michael today, we noticed that a single query gives AP, but MAP should be averaged over all queries. 

For CP6, a "query" is just a label, right? It's nice to have per-label results, but if we're understanding MAP correctly, we should report a single value for each model.

**Comment by mhuesch** [comment]
As per Chad's comment, I've updated the code to say AP where it previously said MAP. I believe this is correct. I also made it print the real MAP.

**Comment by tdietterich** [comment]
This is usually abbreviated as mAP (as opposed to MAP)

--Tom

--
Thomas G. Dietterich, Distinguished Professor Voice: 541-737-5559
School of Electrical Engineering              FAX: 541-737-1300
  and Computer Science                        URL: eecs.oregonstate.edu/~tgd
US Mail: 1148 Kelley Engineering Center
Office: 2067 Kelley Engineering Center
Oregon State Univ., Corvallis, OR 97331-5501

**Comment by cscherrer** [comment]
Thanks @tdietterich , this is much better. Murphy (at least) capitalizes the M, but since we're talking about MAP estimates in so many other contexts, mAP is a better alternative here. We should be sure to use this consistently (docs, code, etc).

**Comment by collinsr** [comment]
I've been working on the scoring code, based off Michael's refactoring. I've added a few more test cases for the actual computation of AP and fixed a semantic bug vis-a-vis the meaning of "correct_map". I also adjusted point (2) in Michael's original comment to this thread to divide by the number of retrieved images, rather than the number of total relevant images (see discussion following.) (Current state is HEAD on MAP_testing.)

I've been validating this vs. the average_precision_score() method supplied by [scikit-learn](scikit-learn.org), and I've run into a question I'm hoping @tdietterich can help with: average precision is defined as a retrieval metric; do we assume that the set of "retrieved" images for some label L is only that set of images whose score is above Lt where Lt is the threshold used for binarization when computing the balanced error rate?

For example, suppose the set of scores is

[ 0.8, 0.2, 0.1, -0.1, -0.3 ]

...and the threshold is 0.05. Do we assert that the threshold implies the process "retrieved" three images and compute average precision over [0.8, 0.2, 0.1], or compute over the whole set of scores? I suspect the former, because all the definitions I've seen of average precision seem to assume that an external process has decided to supply the scores as "possibly relevant" in the first place, i.e. there's no mechanism to apply a cutoff threshold. Either way, it's a small tweak to the compute_AP routine (either to pass the threshold, currently hardwired to 0, or to remove the check entirely.)

As it stands, the code is consistent with what scikit_learn computes given the retrieval assumption above and the dependent assumption that the cutoff threshold is 0.

(Sorry this is taking so long to converge.)

Thanks
-Roddy

**Comment by collinsr** [comment]
I've updated the code to reflect discussion on today's tcon regarding computing AP over the entire return set, and updated the graphs accordingly in the baseline_results directory. @cscherrer, @mhuesch -- if this looks good to you, I'll merge to master and close this issue, and leave it to you to let the teams know about the update.

Thanks
-Roddy

**Comment by mhuesch** [comment]
This looks good to me! I'm a little surprised to see the CRF perform so comparably to the random-binary and random-prior in https://github.com/GaloisInc/ppaml-cp6/blob/MAP_testing/baseline_results/round-1-public-ap.png though. Does that have something to do with the `correct_map` -> `revelant_map` change?

**Comment by collinsr** [comment]
It's a little surprising to us as well... I double-checked that I didn't goof up and that I actually scored the CRF output, etc...

It's entirely possible that the CRF code is borked in some way. I would like to sit down with Eran and have him walk me through the code before the PI meeting, but we probably won't be able to get to that until after the holidays. Given that, do we want to release the CRF scores as-is? Or should we caveat them saying "We are in the process of reviewing the CRF implementation" or something similar? An alternative would be to regenerate the graphs with the AP / mAP corrections but leave off the CRF results and say that they're still pending... opinions?

**Comment by tdietterich** [comment]
Let’s not release the CRF score (or the code) yet. I hope the CRF is broken, given its scores.

Yes, let’s release the graphs with AP / mAP corrections and graphs but leave off the CRF results.

--
Thomas G. Dietterich, Distinguished Professor Voice: 541-737-5559
School of Electrical Engineering              FAX: 541-737-1300
  and Computer Science                        URL: eecs.oregonstate.edu/~tgd
US Mail: 1148 Kelley Engineering Center
Office: 2067 Kelley Engineering Center
Oregon State Univ., Corvallis, OR 97331-5501

**Comment by cscherrer** [comment]
Hi Roddy, is this updated on the [baseline results page](https://github.com/GaloisInc/ppaml-cp6/tree/master/baseline_results)?

**Comment by collinsr** [comment]
I've updated the graphs and readme on the branch; if it looks good on your
side, feel free to merge to master.

Thanks
-Roddy

**Pull request merged**
